name: CI - Who is There

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
        
jobs: 
  test:
    name: Run Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
            python -m pip install --upgraded pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt;

      - name: Lint using flake8
        run:
            |
            pip install flake8
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics     
