name: CI - Python Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          pip install flake8 mypy bandit safety
      
      - name: Lint with flake8
        run: flake8 main.py    

      - name: Type check using mypy
        run: mypy main.py || true

      - name: Static security analysis using Bandit
        run: bandit -r . -x tests
